name: Generate Snake

on:
  schedule: # executa automaticamente todo dia às 00:00
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a Snake
        uses: Platane/snk@v3
        with:
          github_user_name: GustavoVirges
          outputs: dist/snake.svg

      - name: Enviar para o branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
